// newer locations at the front of the array
export const LOCATIONS = [
  {
    city: "Istanbul",
    country: "Türkiye",
    video: "",
    map: "",
    blogPost: "",
    housing: 1131,
    spending: 1387,
  },
  {
    city: "Budapest",
    country: "Hungary",
    video: "",
    map: "",
    blogPost: "",
    housing: 1131,
    spending: 1387,
  },
  {
    city: "Amsterdam",
    country: "Netherlands",
    video: "",
    map: "",
    blogPost: "",
    housing: 1131,
    spending: 1387,
  },
  {
    city: "Lisbon",
    country: "Portugal",
    video: "",
    map: "",
    blogPost: "",
    housing: 1131,
    spending: 1387,
  },
  {
    city: "Hawaii",
    country: "USA",
    video: "",
    map: "",
    blogPost: "",
    housing: 1131,
    spending: 1387,
  },
  {
    city: "DMV (DC, Maryland, Virginia)",
    country: "USA",
    video: "",
    map: "",
    blogPost: "",
    housing: 1131,
    spending: 1387,
  },
  {
    city: "Tamarindo",
    country: "Costa Rica",
    video: "",
    map: "",
    blogPost: "",
    housing: 1131,
    spending: 1387,
  },
  {
    city: "Playa del Carmen",
    country: "Mexico",
    video: "",
    map: "",
    blogPost: "",
    housing: 1131,
    spending: 1387,
  },
  {
    city: "Medellin",
    country: "Colombia",
    video: "",
    map: "",
    blogPost: "",
    housing: 1131,
    spending: 1387,
  },
  {
    city: "New Orleans, Louisiana",
    country: "USA",
    video: "",
    map: "",
    blogPost: "",
    housing: 1131,
    spending: 1387,
  },
  {
    city: "Atlanca, Georgia",
    country: "USA",
    video: "",
    map: "",
    blogPost: "",
    housing: 1131,
    spending: 1387,
  },
  {
    city: "San Juan, Puerto Rico",
    country: "USA",
    video: "",
    map: "",
    blogPost: "",
    housing: 1131,
    spending: 1387,
  },
  {
    city: "Barcelona",
    country: "Spain",
    video: "",
    map: "",
    blogPost: "",
    housing: 1131,
    spending: 1387,
  },
  {
    city: "Chicago, Illinois",
    country: "USA",
    video: "",
    map: "",
    blogPost: "",
    housing: 1131,
    spending: 1387,
  },
  {
    city: "Bay Area, California",
    country: "USA",
    video: "",
    map: "",
    blogPost: "",
    housing: 1131,
    spending: 1387,
  },
  {
    city: "Seattle, Washington",
    country: "USA",
    video: "",
    map: "",
    blogPost: "",
    housing: 1131,
    spending: 1387,
  },
  {
    city: "Mexico City",
    country: "Mexico",
    video: "",
    map: "",
    blogPost: "",
    housing: 1131,
    spending: 1387,
  },
  {
    city: "New York City, New York",
    country: "USA",
    video: "",
    map: "",
    blogPost: "",
    housing: 1131,
    spending: 1387,
  },
  {
    city: "Austin, Texas",
    country: "USA",
    lattitude: 30.26830825183726,
    longitude: -97.74928650508556,
    arrivalDay: '2021-03-28',
    departureDay: '2021-05-01',
    video: "https://www.youtube.com/watch?v=K4k1gXZkJiU",
    map: "https://www.google.com/maps/d/edit?mid=178GA8x6t2ypF9qmBf1VK2rEpXGVq5F_F&usp=sharing",
    blogPost: "https://thequietchew.wordpress.com/2021/07/08/good-morning-austin/",
    personalInstagramPost: null, // acuteengle
    photosPost: null, // b.eng photography
    dancePost: null, // instagram reel
    housing: 1131,
    spending: 1387,
  }
]